# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

version = 1

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "2024 Christoph Sax <c_sax@mailbox.org>"
SPDX-License-Identifier = "EUPL-1.2"
