approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

enableTelemetry: 0

nodeLinker: node-modules

npmMinimalAgeGate: 5d

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32
