# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "t32-language-server-user-guide-data"
description = "Prepares information from user guide for language server consumption"
version = "0.1.0"
authors = ["Christoph Sax <c_sax@mailbox.org>"]
keywords = [
  "language-server",
  "lsp",
  "trace32",
  "lauterbach",
  "practice"
]
categories = [
  "command-line-utilities",
  "development-tools",
  "parsing",
  "text-editors"
]
license = "EUPL-1.2"
repository = "https://codeberg.org/xasc/t32-language-server"
edition = "2024"
rust-version = "1.95"
include = [
  "/src/",
  "/tests/",
  "/LICENSES/",
  "/CHANGELOG.md"
]

[lib]
path = "src/lib.rs"

[[bin]]
name = "t32ls-ugd"
path = "src/bin/serialize/main.rs"

[build-dependencies]
cc=">=1.2.60"

[dependencies]
rmp-serde = "1.3.1"
serde = { version = ">=1.0.215", features = ["derive"] }
serde_json = "1.0.150"
