# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Build language server for OS

on:
  workflow_run:
    workflows: [Generate data assets for language server]
    types:
      - completed

  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      profile:
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ${{ inputs.runner }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v7.0.1

      - name: Build binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Run tests
        run: cargo test --verbose --package t32-language-server
