name: Build language server for OS

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      profile:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build language server
        run: cargo build --verbose --bin t32ls --profile ${{ inputs.profile }}


  test:
    needs: build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Run tests
        run: cargo test --verbose --package t32-language-server
