# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Build language server for OS

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      wasi-version:
        required: true
        type: number
      wasi-os:
        required: true
        type: string
      wasi-arch:
        required: true
        type: string

jobs:
  build:
    name: Build WebAssembly binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build WebAssembly module
        uses: ./.github/actions/build_steps_wasm
        with:
          profile: release
          wasi-version: 32
          wasi-os: linux
          wasi-arch: x86_64
