# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Publish language server crate

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  publish_t32ls_crate:
    name: Publish language server crate
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build language server
        run: cargo build --verbose --bin t32ls

      - name: Run tests
        run: cargo test --verbose --package t32-language-server

      - name: Publish crate dry run
        run: cargo publish --dry-run --package t32-language-server --token "$CARGO_REGISTRY_TOKEN"
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}

      - name: Publish crate
        run: cargo publish --package t32-language-server --token "$CARGO_REGISTRY_TOKEN"
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}
