# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Create binary release packages

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release_t32ls_bin_linux_primary:
    name: Create Linux release
    strategy:
      matrix:
        os: [ {img: ubuntu-latest, flavor: x86_64 } ]
    runs-on: ${{ matrix.os.img }}
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir --parents ./t32ls-linux-${{ matrix.os.flavor }}/
          cp --verbose ./target/release/t32ls ./t32ls-linux-${{ matrix.os.flavor }}/
          tar cvfz t32ls-linux-${{ matrix.os.flavor }}.tar.gz t32ls-linux-${{ matrix.os.flavor }}/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} --notes-from-tag --verify-tag ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz
          gh release list
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_linux_secondary:
    name: Create Linux release
    needs: release_t32ls_bin_linux_primary
    strategy:
      matrix:
        os: [ {img: ubuntu-24.04-arm, flavor: arm64} ]
    runs-on: ${{ matrix.os.img }}
    container: quay.io/pypa/manylinux_2_28_aarch64
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir --parents ./t32ls-linux-${{ matrix.os.flavor }}/
          cp --verbose ./target/release/t32ls ./t32ls-linux-${{ matrix.os.flavor }}/
          tar cvfz t32ls-linux-${{ matrix.os.flavor }}.tar.gz t32ls-linux-${{ matrix.os.flavor }}/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-linux-${{ matrix.os.flavor }}.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_macos:
    name: Create macOS release
    needs: release_t32ls_bin_linux_primary
    strategy:
      matrix:
        os: [ {img: macos-15-intel, flavor: x86_64 }, {img: macos-15, flavor: arm64} ]
    runs-on: ${{ matrix.os.img }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir -p ./t32ls-macos-${{ matrix.os.flavor }}/
          cp ./target/release/t32ls ./t32ls-macos-${{ matrix.os.flavor }}/
          tar cvfz t32ls-macos-${{ matrix.os.flavor }}.tar.gz t32ls-macos-${{ matrix.os.flavor }}/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-macos-${{ matrix.os.flavor }}.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-macos-${{ matrix.os.flavor }}.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-macos-${{ matrix.os.flavor }}.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_win:
    name: Create Windows release
    needs: release_t32ls_bin_linux_primary
    strategy:
      matrix:
        os: [ {img: windows-2022, flavor: win64 }, {img: windows-11-arm, flavor: win-arm64} ]
    runs-on: ${{ matrix.os.img }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir ./t32ls-${{ matrix.os.flavor }}/
          copy ./target/release/t32ls.exe ./t32ls-${{ matrix.os.flavor }}/
          7z a -r t32ls-${{ matrix.os.flavor }}.zip ./t32ls-${{ matrix.os.flavor }}

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./target/release/t32ls.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-${{ matrix.os.flavor }}.zip
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-${{ matrix.os.flavor }}.zip
        env:
          GH_TOKEN: ${{github.token}}

  release_t32_bin_wasm:
    name: Create WebAssembly release
    needs: release_t32ls_bin_linux_primary
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release WebAssembly module
        uses: ./.github/actions/build_steps_wasm
        with:
          profile: release
          wasi-version: 32
          wasi-os: linux
          wasi-arch: x86_64

      - name: Bundle release artifacts
        run: |
          mkdir --parents ./t32ls-wasm32-wasip1-threads/
          cp --verbose ./target/wasm32-wasip1-threads/release/t32ls.wasm ./t32ls-wasm32-wasip1-threads/
          tar cvfz t32ls-wasm32-wasip1-threads.tar.gz t32ls-wasm32-wasip1-threads/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-wasm32-wasip1-threads.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-wasm32-wasip1-threads.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-wasm32-wasip1-threads.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}
