# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2


name: Create binary release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release_t32ls_bin_linux:
    name: Create Linux release
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build language server
        run: |
          cargo build --verbose --bin t32ls --profile=release
          mkdir --parents ./t32ls-linux-x86_64/
          cp --verbose ./target/release/t32ls ./t32ls-linux-x86_64/
          tar cvfz t32ls-linux-x86_64.tar.gz ./t32ls-linux-x86_64/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-linux-x86_64.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-linux-x86_64.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} --notes-from-tag --verify-tag ./t32ls-linux-x86_64.tar.gz
          gh release list
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_macos:
    name: Create macOS release
    needs: release_t32ls_bin_linux
    runs-on: macos-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build language server
        run: |
          cargo build --verbose --bin t32ls --profile=release
          mkdir -p ./t32ls-macos-x86_64/
          cp ./target/release/t32ls ./t32ls-macos-x86_64/
          tar cvfz t32ls-macos-x86_64.tar.gz ./t32ls-macos-x86_64/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-macos-x86_64.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-macos-x86_64.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-macos-x86_64.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_win:
    name: Create Windows release
    needs: release_t32ls_bin_linux
    runs-on: windows-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build language server
        run: |
          cargo build --verbose --bin t32ls --profile=release
          mkdir ./t32ls-win64/
          copy ./target/release/t32ls.exe ./t32ls-win64/
          7z a -r t32ls-win64.zip ./t32ls-win64

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./target/release/t32ls.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-win64.zip
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-win64.zip
        env:
          GH_TOKEN: ${{github.token}}
