# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Create binary release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release_t32ls_bin_linux:
    name: Create Linux release
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir --parents ./t32ls-linux-x86_64/
          cp --verbose ./target/release/t32ls ./t32ls-linux-x86_64/
          tar cvfz t32ls-linux-x86_64.tar.gz t32ls-linux-x86_64/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-linux-x86_64.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-linux-x86_64.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} --notes-from-tag --verify-tag ./t32ls-linux-x86_64.tar.gz
          gh release list
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_macos:
    name: Create macOS release
    needs: release_t32ls_bin_linux
    runs-on: macos-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir -p ./t32ls-macos-x86_64/
          cp ./target/release/t32ls ./t32ls-macos-x86_64/
          tar cvfz t32ls-macos-x86_64.tar.gz t32ls-macos-x86_64/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-macos-x86_64.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-macos-x86_64.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-macos-x86_64.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

  release_t32ls_bin_win:
    name: Create Windows release
    needs: release_t32ls_bin_linux
    runs-on: windows-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release binary
        uses: ./.github/actions/build_steps_os
        with:
          profile: release

      - name: Bundle release artifacts
        run: |
          mkdir ./t32ls-win64/
          copy ./target/release/t32ls.exe ./t32ls-win64/
          7z a -r t32ls-win64.zip ./t32ls-win64

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./target/release/t32ls.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-win64.zip
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.ref_name }} ./t32ls-win64.zip
        env:
          GH_TOKEN: ${{github.token}}

  release_t32_bin_wasm:
    name: Create WebAssembly release
    needs: release_t32ls_bin_linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Build release WebAssembly module
        uses: ./.github/actions/build_steps_wasm
        with:
          profile: release
          wasi-version: 32
          wasi-os: linux
          wasi-arch: x86_64

      - name: Bundle release artifacts
        run: |
          mkdir --parents ./wasm32-wasip1-threads/
          cp --verbose ./target/wasm32-wasip1-threads/release/t32ls.wasm ./t32ls-wasm32-wasip1-threads/
          tar cvfz t32ls-wasm32-wasip1-threads.tar.gz t32ls-wasm32-wasip1-threads/

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./t32ls-wasm32-wasip1-threads.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./t32ls-wasm32-wasip1-threads.tar.gz
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} --notes-from-tag --verify-tag ./t32ls-wasm32-wasip1-threads.tar.gz
          gh release list
        env:
          GH_TOKEN: ${{ github.token }}
