# SPDX-FileCopyrightText: 2024 Christoph Sax <c_sax@mailbox.org>
#
# SPDX-License-Identifier: EUPL-1.2

name: Build and publish VS Code extension

on:
  # Workflow can be triggered manually
  workflow_dispatch:
    inputs:
      t32ls_version:
        description: 'Included server version'
        required: true
        default: 'v0.9.0'
        type: string
      extension_name:
        description: 'Name of the VS Code extension'
        required: true
        default: 't32ls-vsc'
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build_unix:
    name: Build Unix variants
    strategy:
      matrix:
        os: [
          { img: ubuntu-latest, vsce_target: linux-x64, t32ls_flavor: x86_64 },
          { img: ubuntu-latest, vsce_target: linux-arm64, t32ls_flavor: arm64 },
          { img: macos-latest, vsce_target: darwin-x64, t32ls_flavor: x86_64 },
          { img: macos-latest, vsce_target: darwin-arm64, t32ls_flavor: arm64 },
        ]
    runs-on: ${{ matrix.os.img }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Yarn v2
        run: npm install -g corepack

      - name: Install Node.js dependencies
        run: cd vscode && yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download t32ls release
        run: |
          wget https://github.com/xasc/t32-language-server/releases/download/${{ github.event.inputs.t32ls_version }}/t32ls-linux-${{ matrix.os.t32ls_flavor }}.tar.gz
          tar xvf t32ls-linux-${{ matrix.os.t32ls_flavor }}.tar.gz

          mkdir vscode/bin
          cp t32ls-linux-${{ matrix.os.t32ls_flavor }}/* vscode/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update environment variables
        shell: pwsh
        run: echo "target=${{ matrix.os.vsce_target }}" >> $env:GITHUB_ENV

      - name: Build package
        run: cd vscode && yarn run vsce package --skip-license --no-yarn --target ${{ env.target }}

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.event.inputs.t32ls_version }} ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix
        env:
          GH_TOKEN: ${{github.token}}

  build_windows:
    name: Build Windows variants
    strategy:
      matrix:
        os: [
          { img: windows-latest, vsce_target: win32-x64, t32ls_flavor: win64 },
          { img: windows-11-arm, vsce_target: win32-arm64, t32ls_flavor: win-arm64 },
        ]
    runs-on: ${{ matrix.os.img }}
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Yarn v2
        run: corepack enable

      - name: Install Node.js dependencies
        run: cd vscode && yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install wget
        run: choco install wget --no-progress

      - name: Download t32ls release
        run: |
          wget https://github.com/xasc/t32-language-server/releases/download/${{ github.event.inputs.t32ls_version }}/t32ls-${{ matrix.os.t32ls_flavor }}.zip
          7z x t32ls-${{ matrix.os.t32ls_flavor }}.zip

          mkdir vscode/bin
          copy t32ls-${{ matrix.os.t32ls_flavor }}/* vscode/bin/
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update environment variables
        shell: pwsh
        run: echo "target=${{ matrix.os.vsce_target }}" >> $env:GITHUB_ENV

      - name: Build package
        run: cd vscode && yarn run vsce package --skip-license --no-yarn --target ${{ env.target }}

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix
          archive: false
          retention-days: 1

      - name: Create GitHub release
        run: |
          gh release list
          gh release upload ${{ github.event.inputs.t32ls_version }} ./vscode/${{ github.event.inputs.extension_name }}-${{ env.target }}-*.vsix
        env:
          GH_TOKEN: ${{github.token}}

  publish:
    name: Publish extension to registries
    needs: [build_unix, build_windows]
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./vscode

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Yarn v2
        run: corepack enable

      - name: Install Node.js dependencies
        run: cd vscode && yarn install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to Visual Studio Marketplace
        run: cd vscode && yarn run vsce publish --skip-duplicate --skip-license --no-yarn --packagePath $(find . -iname "*.vsix")
        env:
          VSCE_PAT: ${{ secrets.VSMARKETPLACE_TOKEN }}

      - name: Publish package to Open VSX Registry
        run: cd vscode && yarn run ovsx publish --skip-duplicate --pat ${{ secrets.OPENVSX_TOKEN }} --packagePath $(find . -iname "*.vsix")
